### ISSUE TITLE
DB設計(ER図)を作成する

### ISSUE THREAD

**Issue by Paru871** [Paru871/buzzcord#5]
DB設計を行い、ER図を作成する

**Comment by Paru871** [comment]
![スクリーンショット 2022-04-19 22 43 21](https://user-images.githubusercontent.com/82434093/164017518-e7d035ef-c5ec-4c60-9dd1-4cc834d7c30c.png)

**Comment by yoshitsugu** [comment]
- 先週の発言も取得するのであればおなじメッセージAに対して昨日はReactionが5件だったけど今日は10件ついていた、ということがあるかなと思います。その場合って、同じMessage idのものにひもづくReactionが増減するイメージですか？
- 1日の間固定表示であれば、ランキング自体も一旦保存して、とりだして表示するだけにしておくと表示時のサーバー負荷軽減になりそうです。もちろんアプリケーションサーバー側でキャッシュする(都度ランキング集計しないでviewを保存しておく)こともできると思うので、設計はおまかせします。

**Comment by Paru871** [comment]
@yoshitsugu さん、お忙しいなか私の自作サービスのDB設計をレビューしてくださってありがとうございます。

> 先週の発言も取得するのであればおなじメッセージAに対して昨日はReactionが5件だったけど今日は10件ついていた、ということがあるかなと思います。その場合って、同じMessage idのものにひもづくReactionが増減するイメージですか？

書いてくださったような流れを考えていたのですが、提出後によく考えたら、必要なのは「ついたReaction(絵文字)のトータル数」だけなので、別テーブルにReaction(絵文字)の内訳をとっておく必要はなく、Messageテーブルに「Reactionトータル数」として含めて良いかなと考え直しました。

> 1日の間固定表示であれば、ランキング自体も一旦保存して、とりだして表示するだけにしておくと表示時のサーバー負荷軽減になりそうです。もちろんアプリケーションサーバー側でキャッシュする(都度ランキング集計しないでviewを保存しておく)こともできると思うので、設計はおまかせします。

確かに書いてくださったとおりだと思いました。
計算結果のランキングだけを別DBに保存するようにします。

-----

上記のことを踏まえて、DB設計を修正いたしましたので、再度チェックをいただきたく、よろしくお願いいたします。

【DB設計の修正版】

[ペーパープロトタイプ](https://bootcamp.fjord.jp/products/11852)

ER図を作成しました。
![スクリーンショット 2022-04-29 22 02 25](https://user-images.githubusercontent.com/82434093/165950174-e6c7d588-7c16-42d2-afbd-1dfac62e5e28.png)


- 全データを削除後、昨日〜7日前までの発言を取得する(毎日1回バッチ処理)  →Messagesテーブルへ保存
- 取得したデータを集計 →Rankingsテーブルへ保存、categoryカラムにはd(昨日)とw(週)の区分を入れる
- 毎日1回、定時に「昨日最もバズった発言」をbotがDiscordでお知らせ
- サイトでは「昨日バズった発言ベスト5」と「先週バズった発言ベスト5」を表示 
→ (現在検討中の事項)ファーストリリース時はサイトでの閲覧ではなくdiscord botを呼び出して知りたいランクをbotに発言させ(RailsはAPI専用として使用)、サイト表示は今後の機能拡大に合わせて作成することも考えています。
- 「昨日バズった発言ベスト5」の定義 ⇒「昨日投稿された発言」でついた絵文字の総数が上位5つ

**Comment by yoshitsugu** [comment]
確認しました！
ペーパープロトタイプを見る限り、リアクションの種類ごとの数も表示していそうですが、total_numberだけで大丈夫そうでしょうか？

**Comment by Paru871** [comment]
@yoshitsugu さん、DB設計のご確認いただきありがとうございます。

> ペーパープロトタイプを見る限り、リアクションの種類ごとの数も表示していそうですが、total_numberだけで大丈夫そうでしょうか？

気付いてくださってありがとうございます！
DB設計を考えていたら、自分で書いたペーパープロトタイプの内容と合わなくなってしまっていました💦
書いてくださったとおり「リアクションの種類ごとの数」が必要ですので、Reactionsテーブルを戻しますね。

-----

上記のことを踏まえて、DB設計を再度修正いたしましたので、お手数をおかけしますがチェックをいただきたくよろしくお願いいたします。

【DB設計の修正版】

[ペーパープロトタイプ](https://bootcamp.fjord.jp/products/11852)

ER図を作成しました。
![スクリーンショット 2022-04-30 21 26 47](https://user-images.githubusercontent.com/82434093/166105979-b3ab999c-871d-4df0-abf5-74c0387eed98.png)

- 全データを削除後、昨日〜7日前までの発言と発言に紐づくReactionを取得する(発言の修正や削除、Reaction数の変化があるので毎日1回バッチ処理でデータを取得し直す)  →MessagesテーブルとReactionsテーブルへ保存
- 取得したデータを集計 →Rankingsテーブルへ保存、categoryカラムにはd(昨日)とw(週)の区分を入れる
- 毎日1回、定時に「昨日最もバズった発言」をbotがDiscordでお知らせ
- サイトでは「昨日バズった発言ベスト5」と「先週バズった発言ベスト5」を表示 
→ (現在検討中の事項)ファーストリリース時はサイトでの閲覧ではなくdiscord botを呼び出して知りたいランクをbotに発言させ(RailsはAPI専用として使用)、サイト表示は今後の機能拡大に合わせて作成することも考えています。
- 「昨日バズった発言ベスト5」の定義 ⇒「昨日投稿された発言」でついた絵文字の総数が上位5つ

**Comment by yoshitsugu** [comment]
いいと思います :ok_man:

**Comment by Paru871** [comment]
ありがとうございました。
OKをいただけましたのでこちらはクローズとさせていただきます〜🌈

**Comment by Paru871** [comment]
クローズ後ですが、データの取得方法を変更したのでDB設計を修正しました。
![image](https://user-images.githubusercontent.com/82434093/169740542-c0b5bd48-9f7d-4037-a6fb-43935c8f62a9.png)

- botをdiscordへ常駐させて、公開されているチャンネルを監視し、Reaction絵文字が付加・削除されるごとにReactionsテーブルへ保存
- 日付が変わったら前日分のReactionsデータを集計(バッチ処理) →Ranksテーブルへ保存(Emojisへは発言についた絵文字の種類とその数、Attachmentsへは発言に添付されているファイル情報を保存)
- 毎日1回、定時に「昨日最もバズった発言」をbotがDiscordでお知らせ
- サイトでは「昨日バズった発言ベスト5」を表示
- 「昨日バズった発言ベスト5」の定義 ⇒「昨日リアクションされた絵文字の数」が上位の発言5つ
